version: '3.8'
services:
  mysql-chat-service:
    image: mysql:8.0
    container_name: mysql-chat-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_chat_data:/var/lib/mysql
    networks:
      - mynetwork

  mysql-room-service:
    image: mysql:8.0
    container_name: mysql-room-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: roomdb
      MYSQL_USER: roomuser
      MYSQL_PASSWORD: roompassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_room_data:/var/lib/mysql
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-chat-db  # Verweist auf den Container-Namen
      PMA_PORT: 3306  # MySQL läuft innerhalb des Containers auf Port 3306
    ports:
      - "8081:80"
    networks:
      - mynetwork

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
      PMA_HOST: mysql-room-db  # Verweist auf den Container-Namen
      PMA_PORT: 3306  # MySQL läuft innerhalb des Containers auf Port 3306
    ports:
      - "8082:80"
    networks:
      - mynetwork


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  user-service:
    build:
      context: ./BackEnd/user-service
    container_name: user-service
    depends_on:
      - rabbitmq
      - mysql-chat-service
    ports:
      - "5175:80"
    networks:
      - mynetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySqlConnection=server=mysql-chat-db;port=3306;database=chatdb;user=chatuser;password=chatpassword

  chat-service:
    build:
      context: ./BackEnd/chat-service
    container_name: chat-service
    depends_on:
      - rabbitmq
      - mysql-chat-service
    ports:
      - "5176:80"
    networks:
      - mynetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySqlConnection=server=mysql-chat-db;port=3306;database=chatdb;user=chatuser;password=chatpassword

  room-service:
    build:
      context: ./BackEnd/room-service
    container_name: room-service
    depends_on:
      - rabbitmq
      - mysql-room-service
    ports:
      - "5177:80"
    networks:
      - mynetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySqlConnection=server=mysql-room-db;port=3306;database=roomdb;user=roomuser;password=roompassword
      - RabbitMQ__Host=rabbitmq

  frontend:
    build:
      context: ./FrontEnd
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork


volumes:
  mysql_chat_data:
  mysql_room_data:

networks:
  mynetwork: